/**
 * Timezone-aware scheduling helpers.
 *
 * The nightly job runs hourly. On each run we generate a story for every child
 * whose local time has reached their "generation window" — a lead time before
 * their bedtime — and who doesn't yet have tonight's story. Because generation
 * is idempotent per (child, local date), a child becomes due once their local
 * time crosses the window and is generated by the first hourly run after that;
 * later runs skip them. A failed run simply retries next hour.
 */

export const DEFAULT_LEAD_MINUTES = 120;

export function leadMinutes(): number {
  const raw = Number(process.env.GENERATION_LEAD_MINUTES);
  return Number.isFinite(raw) && raw >= 0 ? raw : DEFAULT_LEAD_MINUTES;
}

/** Minutes-since-local-midnight for a timezone at `now` (DST-correct via Intl). */
export function localMinutesOfDay(timezone: string, now = new Date()): number {
  const parts = new Intl.DateTimeFormat("en-GB", {
    timeZone: timezone,
    hour: "2-digit",
    minute: "2-digit",
    hourCycle: "h23",
  }).formatToParts(now);
  const hour = Number(parts.find((p) => p.type === "hour")?.value ?? "0");
  const minute = Number(parts.find((p) => p.type === "minute")?.value ?? "0");
  return hour * 60 + minute;
}

/** Parse "HH:mm" to minutes-since-midnight; falls back to 19:30 if malformed. */
export function parseHHmm(value: string): number {
  const m = /^(\d{1,2}):(\d{2})$/.exec(value.trim());
  if (!m) return 19 * 60 + 30;
  const h = Math.min(23, Math.max(0, Number(m[1])));
  const min = Math.min(59, Math.max(0, Number(m[2])));
  return h * 60 + min;
}

/**
 * Is this child due for tonight's story right now? True once their local time
 * has reached (bedtime − lead). The generation window stays open until local
 * midnight so a missed hour still gets picked up; the existing-story check
 * upstream keeps it to one generation per night.
 */
export function isChildDue(
  child: { bedtimeLocal: string; timezone: string },
  now = new Date(),
  lead = leadMinutes()
): boolean {
  const bedtime = parseHHmm(child.bedtimeLocal);
  const target = Math.max(0, bedtime - lead);
  const localNow = localMinutesOfDay(child.timezone, now);
  return localNow >= target;
}

/** Minutes until this child's bedtime in their timezone (negative if passed). */
export function minutesUntilBedtime(
  child: { bedtimeLocal: string; timezone: string },
  now = new Date()
): number {
  return parseHHmm(child.bedtimeLocal) - localMinutesOfDay(child.timezone, now);
}
